export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold text-neutral-800 mb-6 font-heading">Terms of Service</h1>

      <div className="prose prose-neutral">
        <p className="text-muted-foreground mb-6">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">1. Introduction</h2>
        <p className="mb-4">
          Welcome to CupLog. By using our website and services, you agree to comply with and be bound by the following terms and conditions. Please review them carefully before using the platform.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">2. Acceptance of Terms</h2>
        <p className="mb-4">
          By accessing or using CupLog, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">3. Description of Service</h2>
        <p className="mb-4">
          CupLog provides a digital platform for performing SCA-standard coffee cupping evaluations. Users can create cupping sessions, score coffees using SCA methodology, store session history, and analyze quality trends over time.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">4. User Accounts</h2>
        <p className="mb-4">
          Some features require you to create an account via Google or Discord OAuth. You are responsible for maintaining the confidentiality of your account and for all activities that occur under it. Notify us immediately if you suspect unauthorized use.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">5. User Content</h2>
        <p className="mb-4">
          You retain ownership of all cupping data you enter into CupLog. By using the service, you grant us a non-exclusive license to store and process this data for the purpose of providing the service.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">6. Prohibited Uses</h2>
        <p className="mb-4">
          You agree not to use CupLog for any unlawful purpose or in any way that could damage or impair our service. Prohibited activities include:
        </p>
        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>Attempting to gain unauthorized access to our systems</li>
          <li>Using the service for any fraudulent or illegal purpose</li>
          <li>Interfering with other users&apos; access to the service</li>
          <li>Uploading malicious code or content</li>
        </ul>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">7. Limitation of Liability</h2>
        <p className="mb-4">
          CupLog is provided &ldquo;as is&rdquo; without warranties of any kind. We are not responsible for any losses or damages resulting from your use of our service, including any cupping evaluations or business decisions made based on scores generated by the platform.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">8. Changes to Terms</h2>
        <p className="mb-4">
          We reserve the right to modify these terms at any time. Significant changes will be communicated by posting updated terms on this page.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">9. Governing Law</h2>
        <p className="mb-4">
          These terms shall be governed by and construed in accordance with applicable laws.
        </p>

        <h2 className="text-xl font-semibold text-neutral-800 mt-8 mb-4">10. Contact Us</h2>
        <p className="mb-4">
          If you have any questions about these Terms, please contact us via <a href="mailto:office@graycup.org" className="text-blue-700 underline">office@graycup.org</a>.
        </p>
      </div>
    </div>
  );
}
